export const environment = {
  appIdCustomer: 'BookOneCustomerApp',
  sessionAppId: 'BOOKONE_MOBILE_APP_CUSTOMER',
  production: true,
  appId: 'TheHotelMate',
  spaceId:'99i7n5tw4eq0',
  accessToken:'q0iVR3edz6GByDVpTdYxTwOsL2yhXA2aApPWKw_7mYk',
  nzAPIUrl: 'https://api.uat.thehotelmate.co',
  // homeAddress: "https://bookonepms.com",
  inAPIUrl: 'https://api.uat.thehotelmate.co',
  hdfcAPIUrl:'https://payment.bookone.io',
  apiScheduler: 'https://scheduler.uat.bookone.io',
  apiUrlAddress: 'https://api.uat.bookone.io/address',
  apiUrlPromotion: 'https://api.uat.bookone.io/promotion',
  apiLms: 'https://api.uat.bookone.io/lms',
  channelIntegration:'https://channel-integration.uat.bookone.io',
  apiUrlBookone: 'https://api.uat.bookone.io/api',
  // nzAPIUrl: 'https://testconnect.bookone.io/hotelmate',
  // inAPIUrl: 'https://testconnect.bookone.io/hotelmate',
  // apiScheduler: 'https://testapi.bookonelocal.co.nz/api-scheduler',
  // apiUrlAddress: 'https://testapi.bookonelocal.co.nz/api-address',
  // apiUrlPromotion: 'https://testapi.bookonelocal.co.nz/promotion-api',
  // apiLms: 'https://testapi.bookonelocal.co.nz/api-lms',
  parentOrganisationId: 1,
  dashboardUrl: 'https://app.bookonelocal.in',
  apiUrl: "https://api.uat.thehotelmate.co",
  apiUrlOne: "https://api.bookonelocal.in/api-bookone",
  appUrl: 'https://thehotelmate.co',
  androidAppUrl: 'https://play.google.com/store/apps/details?id=nz.co.bookonelocal.customer',
  iosAppUrl: 'https://apps.apple.com/us/app/bookone-local/id1528910778',
  country: 'in',
  googleKey: '',
  // callbackUrl: 'http://localhost:4200/#/details?ReferenceNumber='
  callbackUrl: 'https://thehotelmate.co/booking-confirm',
  callbackUrlPayment:'https://bookone.io/confirm-payment'

};
