export const environment = {
  appIdCustomer: 'BookOneCustomerApp',
  sessionAppId: 'BOOKONE_MOBILE_APP_CUSTOMER',
  production: true,
  appId: 'TheHotelMate',
  spaceId: '99i7n5tw4eq0',
  accessToken: 'q0iVR3edz6GByDVpTdYxTwOsL2yhXA2aApPWKw_7mYk',
  nzAPIUrl: 'https://api.thehotelmate.com',
  inAPIUrl: 'https://api.thehotelmate.com',
  hdfcAPIUrl: 'https://payment.bookone.io',
  apiScheduler: 'https://api.bookonelocal.in/api-scheduler',
  apiUrlAddress: 'https://api.bookonelocal.in/api-address',
  apiUrlPromotion: 'https://api.bookonelocal.in/promotion-api',
  apiLms: 'https://api.bookonelocal.in/api-lms',
  apiUrlBookone: 'https://api.bookonelocal.in/api-bookone',
  // nzAPIUrl: 'https://testconnect.bookone.io/hotelmate',
  // inAPIUrl: 'https://testconnect.bookone.io/hotelmate',
  // apiScheduler: 'https://testapi.bookonelocal.co.nz/api-scheduler',
  // apiUrlAddress: 'https://testapi.bookonelocal.co.nz/api-address',
  // apiUrlPromotion: 'https://testapi.bookonelocal.co.nz/promotion-api',
  // apiLms: 'https://testapi.bookonelocal.co.nz/api-lms',
  parentOrganisationId: 1,
  dashboardUrl: 'https://app.bookonelocal.in',
  appUrl: 'https://thehotelmate.com',
  androidAppUrl:
    'https://play.google.com/store/apps/details?id=nz.co.bookonelocal.customer',
  iosAppUrl: 'https://apps.apple.com/us/app/bookone-local/id1528910778',
  country: 'in',
  googleKey: 'AIzaSyD76Ocky2MYrAcI-f9H3XbxzsrSB0TsbJI',
  channelIntegration:'https://api.bookonelocal.in/channel-integration',
  // callbackUrl: 'http://localhost:4200/#/details?ReferenceNumber='
  // callbackUrl: 'http://localhost:4200/booking-complete?ReferenceNumber=',
  callbackUrl: 'https://bookonepms.com/booking-complete?ReferenceNumber=',
};
