export const environment = {
  appIdCustomer: 'BookOneCustomerApp',
  sessionAppId: 'BOOKONE_MOBILE_APP_CUSTOMER',
  production: true,
  appId: 'TheHotelMate',
  spaceId:'99i7n5tw4eq0',
  accessToken:'q0iVR3edz6GByDVpTdYxTwOsL2yhXA2aApPWKw_7mYk',
  nzAPIUrl: 'https://api.uat.thehotelmate.com',
  // homeAddress: "https://bookonepms.com",
  inAPIUrl: 'https://api.uat.thehotelmate.com',
  hdfcAPIUrl:'https://payment.bookone.io',
  apiScheduler: 'https://api.bookone.io/api-scheduler',
  apiUrlAddress: 'https://api.bookone.io/api-address',
  apiUrlPromotion: 'https://api.bookone.io/promotion-api',
  apiLms: 'https://api.bookone.io/api-lms',
  channelIntegration:'https://api.bookone.io/channel-integration',
  apiUrlBookone: 'https://api.bookone.io/api-bookone',
  // nzAPIUrl: 'https://testconnect.bookone.io/hotelmate',
  // inAPIUrl: 'https://testconnect.bookone.io/hotelmate',
  // apiScheduler: 'https://testapi.bookonelocal.co.nz/api-scheduler',
  // apiUrlAddress: 'https://testapi.bookonelocal.co.nz/api-address',
  // apiUrlPromotion: 'https://testapi.bookonelocal.co.nz/promotion-api',
  // apiLms: 'https://testapi.bookonelocal.co.nz/api-lms',
  parentOrganisationId: 1,
  dashboardUrl: 'https://app.bookonelocal.in',
  apiUrl: "https://api.uat.thehotelmate.com",
  apiUrlOne: "https://api.bookone.io/api-bookone",
  appUrl: 'https://thehotelmate.com',
  androidAppUrl: 'https://play.google.com/store/apps/details?id=nz.co.bookonelocal.customer',
  iosAppUrl: 'https://apps.apple.com/us/app/bookone-local/id1528910778',
  country: 'in',
  googleKey: '',
  // callbackUrl: 'http://localhost:4200/#/details?ReferenceNumber='
  callbackUrl: 'http://localhost:4200/confirm',
  callbackUrlPayment:'https://bookone.io/confirm-payment'
};
