export const environment = {
  appIdCustomer: 'BookOneCustomerApp',
  sessionAppId: 'BOOKONE_MOBILE_APP_CUSTOMER',
  production: true,
  appId: 'TheHotelMate',
  spaceId:'99i7n5tw4eq0',
  accessToken:'q0iVR3edz6GByDVpTdYxTwOsL2yhXA2aApPWKw_7mYk',
  // nzAPIUrl: 'https://api.thehotelmate.com',
  // homeAddress: "https://bookonepms.com",
  // inAPIUrl: 'https://api.thehotelmate.com',
  hdfcAPIUrl:'https://payment.bookone.io',
  // apiScheduler: 'https://api.bookonelocal.in/api-scheduler',
  // apiUrlAddress: 'https://api.bookonelocal.in/api-address',
  // apiUrlPromotion: 'https://api.bookonelocal.in/promotion-api',
  // apiLms: 'https://api.bookonelocal.in/api-lms',
  apiUrlBookone: 'https://api.uat.bookone.io/api',
  nzAPIUrl: 'https://api.uat.thehotelmate.com',
  inAPIUrl: 'https://api.uat.thehotelmate.com',
  apiScheduler: 'https://scheduler-api.uat.thehotelmate.com',
  apiUrlAddress: 'https://api.uat.bookone.io/address',
  apiUrlPromotion: 'https://api.uat.bookone.io/promotion',
  apiLms: 'https://api.uat.bookone.io/lms',
  parentOrganisationId: 1,
  dashboardUrl: 'https://app.bookonelocal.in',
  apiUrl: "https://api.uat.thehotelmate.com",
  appUrl: 'https://api.uat.thehotelmate.com',
  androidAppUrl: 'https://play.google.com/store/apps/details?id=nz.co.bookonelocal.customer',
  iosAppUrl: 'https://apps.apple.com/us/app/bookone-local/id1528910778',
  country: 'in',
  googleKey: 'AIzaSyBYGJ1SMIW5BIny9Af7eoozmgSGZShhUuE',
  // callbackUrl: 'http://localhost:4200/#/details?ReferenceNumber='
  callbackUrl: 'https://bookonepms.com/booking-complete?ReferenceNumber='
};
